# Generated by Echo reconstruction on 2026-08-06
import uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import echo.apps.authentication.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('language', models.CharField(default='en', max_length=12)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/%Y/%m/')),
                ('bio', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={'abstract': False},
            managers=[('objects', echo.apps.authentication.models.UserManager())],
        ),
        migrations.CreateModel(name='Permission', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('name', models.CharField(max_length=150)), ('codename', models.CharField(max_length=150, unique=True)), ('description', models.TextField(blank=True)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='UserRole', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('name', models.CharField(max_length=100, unique=True)), ('description', models.TextField(blank=True)), ('is_system', models.BooleanField(default=False)),
        ], options={'ordering': ('-created_at',)}),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.userrole'),
        ),
        migrations.CreateModel(name='UserProfile', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('theme', models.CharField(default='system', max_length=20)), ('accent_color', models.CharField(default='indigo', max_length=20)),
            ('font_size', models.CharField(default='medium', max_length=20)), ('dashboard_layout', models.JSONField(blank=True, default=dict)),
            ('preferred_language', models.CharField(default='en', max_length=12)), ('preferred_ai_model', models.CharField(blank=True, max_length=255)),
            ('notification_preferences', models.JSONField(blank=True, default=dict)), ('timezone', models.CharField(default='UTC', max_length=64)),
            ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='UserDevice', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('device_name', models.CharField(blank=True, max_length=255)), ('browser', models.CharField(blank=True, max_length=255)), ('operating_system', models.CharField(blank=True, max_length=255)),
            ('ip_address', models.GenericIPAddressField(blank=True, null=True)), ('location', models.CharField(blank=True, max_length=255)), ('trusted', models.BooleanField(default=False)), ('last_login', models.DateTimeField(blank=True, null=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',), 'constraints': [models.UniqueConstraint(fields=('user', 'device_name'), name='unique_user_device_name')]}),
        migrations.CreateModel(name='LoginHistory', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('ip_address', models.GenericIPAddressField(blank=True, null=True)), ('browser', models.CharField(blank=True, max_length=255)), ('device', models.CharField(blank=True, max_length=255)),
            ('country', models.CharField(blank=True, max_length=2)), ('city', models.CharField(blank=True, max_length=120)), ('status', models.CharField(default='success', max_length=32)),
            ('login_time', models.DateTimeField(default=django.utils.timezone.now)), ('logout_time', models.DateTimeField(blank=True, null=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='EmailVerificationToken', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('token_hash', models.CharField(max_length=64, unique=True)), ('expires_at', models.DateTimeField(db_index=True)), ('used', models.BooleanField(default=False)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='PasswordResetToken', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('token_hash', models.CharField(max_length=64, unique=True)), ('expires_at', models.DateTimeField(db_index=True)), ('used', models.BooleanField(default=False)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='APIToken', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('token_prefix', models.CharField(db_index=True, max_length=12)), ('token_hash', models.CharField(max_length=64, unique=True)), ('name', models.CharField(max_length=120)),
            ('expires_at', models.DateTimeField(blank=True, null=True)), ('last_used', models.DateTimeField(blank=True, null=True)), ('revoked', models.BooleanField(default=False)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='UserSession', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('session_key', models.CharField(max_length=64, unique=True)), ('ip_address', models.GenericIPAddressField(blank=True, null=True)), ('browser', models.CharField(blank=True, max_length=255)),
            ('device', models.CharField(blank=True, max_length=255)), ('expires_at', models.DateTimeField(db_index=True)), ('active', models.BooleanField(default=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ('-created_at',)}),
        migrations.CreateModel(name='RolePermission', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='authentication.permission')),
            ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='authentication.userrole')),
        ], options={'ordering': ('-created_at',), 'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission')]}),
    ]
