# Generated by Echo reconstruction on 2026-08-06
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflow records'},
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Workflow Execution', 'verbose_name_plural': 'Workflow Execution records'},
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Workflow Step', 'verbose_name_plural': 'Workflow Step records'},
        ),
        migrations.CreateModel(
            name='StepDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Step Dependency', 'verbose_name_plural': 'Step Dependency records'},
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Execution Event', 'verbose_name_plural': 'Execution Event records'},
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Checkpoint', 'verbose_name_plural': 'Checkpoint records'},
        ),
        migrations.CreateModel(
            name='RetryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Retry History', 'verbose_name_plural': 'Retry History records'},
        ),
    ]
