# Generated by Echo reconstruction on 2026-08-06
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspace records'},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Project', 'verbose_name_plural': 'Project records'},
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('roles', models.CharField(max_length=255, blank=True, db_index=False)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Member', 'verbose_name_plural': 'Project Member records'},
        ),
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Label', 'verbose_name_plural': 'Project Label records'},
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Milestone', 'verbose_name_plural': 'Project Milestone records'},
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Activity', 'verbose_name_plural': 'Project Activity records'},
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Settings', 'verbose_name_plural': 'Project Settings records'},
        ),
    ]
