# Generated by Echo reconstruction on 2026-08-06
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Document', 'verbose_name_plural': 'Document records'},
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Document Metadata', 'verbose_name_plural': 'Document Metadata records'},
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Document Content', 'verbose_name_plural': 'Document Content records'},
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Document Page', 'verbose_name_plural': 'Document Page records'},
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Document Version', 'verbose_name_plural': 'Document Version records'},
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Document Tag', 'verbose_name_plural': 'Document Tag records'},
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Processing Job', 'verbose_name_plural': 'Processing Job records'},
        ),
    ]
