# Generated by Echo reconstruction on 2026-08-06
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'User Setting', 'verbose_name_plural': 'User Setting records'},
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Setting records'},
        ),
        migrations.CreateModel(
            name='FeaturePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Feature Preference', 'verbose_name_plural': 'Feature Preference records'},
        ),
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Integration Setting', 'verbose_name_plural': 'Integration Setting records'},
        ),
        migrations.CreateModel(
            name='SecretReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Secret Reference', 'verbose_name_plural': 'Secret Reference records'},
        ),
        migrations.CreateModel(
            name='ConfigurationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Configuration Audit', 'verbose_name_plural': 'Configuration Audit records'},
        ),
    ]
