# Generated by Echo reconstruction on 2026-08-06
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notification records'},
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification Channel', 'verbose_name_plural': 'Notification Channel records'},
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification Preference', 'verbose_name_plural': 'Notification Preference records'},
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification Template', 'verbose_name_plural': 'Notification Template records'},
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Delivery Log', 'verbose_name_plural': 'Delivery Log records'},
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(max_length=100, blank=True, db_index=True)),
                ('configuration', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification Digest', 'verbose_name_plural': 'Notification Digest records'},
        ),
    ]
