# Generated for Echo computer-use runtime on 2026-08-07
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internet", "0001_initial"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_owned", to=settings.AUTH_USER_MODEL)),
                ("engine", models.CharField(db_index=True, default="chrome", max_length=32)),
                ("headless", models.BooleanField(default=False)),
                ("current_url", models.URLField(blank=True, max_length=4096)),
                ("current_title", models.CharField(blank=True, max_length=512)),
                ("active_tab_handle", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ("-created_at",), "verbose_name": "Browser Session", "verbose_name_plural": "Browser Sessions"},
        ),
        migrations.CreateModel(
            name="BrowserObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_owned", to=settings.AUTH_USER_MODEL)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("url", models.URLField(blank=True, max_length=4096)),
                ("page_title", models.CharField(blank=True, max_length=512)),
                ("visible_text", models.TextField(blank=True)),
                ("dom", models.JSONField(blank=True, default=dict)),
                ("accessibility_tree", models.JSONField(blank=True, default=dict)),
                ("viewport", models.JSONField(blank=True, default=dict)),
                ("media", models.JSONField(blank=True, default=list)),
                ("screenshot", models.FileField(blank=True, upload_to="browser/observations/%Y/%m/%d/")),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("observed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="internet.browsersession")),
            ],
            options={"ordering": ("-created_at",), "verbose_name": "Browser Observation", "verbose_name_plural": "Browser Observations"},
        ),
        migrations.CreateModel(
            name="ComputerUseOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_owned", to=settings.AUTH_USER_MODEL)),
                ("request_text", models.TextField()),
                ("plan", models.JSONField(blank=True, default=list)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("current_operation", models.CharField(blank=True, max_length=255)),
                ("current_tool", models.CharField(blank=True, max_length=120)),
                ("cancellable", models.BooleanField(default=True)),
                ("cancel_requested", models.BooleanField(db_index=True, default=False)),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="computer_use_operations", to="chat.conversation")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="operations", to="internet.browsersession")),
            ],
            options={"ordering": ("-created_at",), "verbose_name": "Computer Use Operation", "verbose_name_plural": "Computer Use Operations"},
        ),
        migrations.CreateModel(
            name="BrowserAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_owned", to=settings.AUTH_USER_MODEL)),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("target", models.TextField(blank=True)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("verified", models.BooleanField(db_index=True, default=False)),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("post_observation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions_after", to="internet.browserobservation")),
                ("pre_observation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions_before", to="internet.browserobservation")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="internet.browsersession")),
            ],
            options={"ordering": ("-created_at",), "verbose_name": "Browser Action", "verbose_name_plural": "Browser Actions"},
        ),
        migrations.CreateModel(
            name="MediaUnderstanding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_owned", to=settings.AUTH_USER_MODEL)),
                ("source_url", models.URLField(blank=True, max_length=4096)),
                ("media_metadata", models.JSONField(blank=True, default=dict)),
                ("transcript", models.TextField(blank=True)),
                ("visual_notes", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("confidence", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("processed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("operation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_understandings", to="internet.computeruseoperation")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_understandings", to="internet.browsersession")),
            ],
            options={"ordering": ("-created_at",), "verbose_name": "Media Understanding", "verbose_name_plural": "Media Understandings"},
        ),
        migrations.AddIndex(model_name="browsersession", index=models.Index(fields=["owner", "status", "-last_activity_at"], name="browser_session_owner_state")),
        migrations.AddIndex(model_name="browserobservation", index=models.Index(fields=["session", "-sequence"], name="browser_observation_seq")),
        migrations.AddIndex(model_name="browseraction", index=models.Index(fields=["session", "-created_at"], name="browser_action_recent")),
        migrations.AddIndex(model_name="computeruseoperation", index=models.Index(fields=["owner", "status", "-updated_at"], name="computer_use_owner_state")),
        migrations.AddIndex(model_name="mediaunderstanding", index=models.Index(fields=["owner", "-processed_at"], name="media_understanding_recent")),
    ]
